src/components/Navbar.tsx
src/contexts/UserContext.tsx
src/main.tsx
src/routes/login.tsx
src/routes/register.tsx

Setting up logout in front and usercontext for the navbar. 
modifié :         src/components/Navbar.tsx
nouveau fichier : src/contexts/UserContext.tsx
modifié :         src/main.tsx
modifié :         src/routes/login.tsx
modifié :         src/routes/register.tsx
[- [e02-t02_account-creation](https://www.notion.so/e02-t02_account-creation-f18310e53e974d65aa663dcedce305d7)](https://www.notion.so/e02-t05_account-disconnexion-cbd083d3ec584793971d7186a60af2a2)

E02 t05 logout

---

src/components/Navbar.tsx
src/contexts/UserContext.tsx
src/main.tsx
src/routes/home.tsx
src/routes/login.tsx
src/routes/register.tsx

Implementation of the register, login and logout system.

Epic02 login

---

src/App.tsx
src/components/Toaster.tsx
src/contexts/NotificationContext.tsx
src/main.tsx
src/routes/register.tsx

We needed a way to display messages / notifications to user upon different actions. -> A Toaster was born !
Created a Notification Context which wraps the App component, so each of its children can call the
```javascript
setMessage{text:'This is some text', type:'info'} 
```
function from the NotificationContext. The Toaster is located « just under » the navbar in App.tsx
- App.tsx
- Toaster.tsx
- main.tsx
- NotificationContext.tsx
- [e02-t08_toaster](https://enchanting-triangle-00d.notion.site/e02-08_toaster-3cd29677b2714fa682bbcb16efc4ed90)

E02 t08 toaster

---

package-lock.json
package.json
src/components/inputs/inputsInterfaces.ts
src/routes/login.tsx
src/routes/register.tsx
src/utils/schemaValidation.ts

Add react hook form and yup schema validation for register and login form
Add RHF and yup packages
Add shema and interfaces for register and login forms
src/routes/register.tsx
src/routes/login.tsx
src/utils/schemaValidation.ts
src/components/inputs/inputsInterfaces.ts
- [e02-t06: rhf integration](https://www.notion.so/e02-t06_rhf-integration-31b57878d7f8444b907fc8932d69d75d)
- [e02-t07: yup integration](https://www.notion.so/e02-07_yup-validation-bd773410d68f4bf78f229ab208a7358f)

E02 t06 rhf integration

---

package-lock.json
package.json
src/App.tsx
src/components/Navbar.tsx
src/components/Toaster.tsx
src/components/createblog/StepThree.tsx
src/components/createblog/StepTwo.tsx
src/components/inputs/ProgressionBar.tsx
src/components/inputs/inputsInterfaces.ts
src/contexts/NotificationContext.tsx
src/contexts/UserContext.tsx
src/main.tsx
src/routes/createblog.tsx
src/routes/home.tsx
src/routes/login.tsx
src/routes/register.tsx
src/utils/blogValidation.ts
src/utils/schemaValidation.ts

Deux premières pages qui apparaissent suite au clic sur “Créer mon blog” sur la page d’accueil
- AJout d'un isCreatingBlog state dans UserContext pour bloquer la redirection automatique vers home après la connexion du user quand il est sur la page de création de blog
- Schéma de validation du nom et de la description avec yup
- Création de blog
- CSS rudimentaire
- createblog
- StepTwo
- StepThree
- UserContext
- login
- utils/blogValidation
- [e04-t03]
- [ x] New feature (feat)
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my PR
- [x ] I have been able to build my solution locally
- [x ] My changes generate no new warnings

E04 t03 blog creation steps one two

---

src/components/createblog/StepTwo.tsx
src/routes/createblog.tsx

Removed comments and added Prettier format
//
- StepTwo
- CreateBlog
- [e04-t07:](link to issue)

fix(e04-t07): delete coms and format with prettier

---

src/components/buttons/DeleteUser.tsx
src/routes/profile.tsx

A user must be able to delete his account
Add delete button on profile to delete user account. 
src/components/routes/profile.tsx
src/components/buttons/DeleteUser.tsx
- [e03-t06](https://www.notion.so/e03-t06_profile-delete-003e4125941a45449a5a838327e8cbac)

feat(e03-t06): add delete button for user account

---

index.html
package-lock.json
package.json
src/App.tsx
src/components/Card.tsx
src/components/Toaster.tsx
src/routes/blogs/BlogT1.tsx
src/routes/blogs/ListingBlogs.tsx
src/routes/blogs/blogs.tsx
src/routes/blogs/singleblog.tsx
src/routes/createblog.tsx
src/routes/home.tsx
src/routes/singleArticle.tsx
src/utils/interfaces/Interfaces.ts
src/utils/ouputContentBlocks.tsx

Display data from backend on home, blogs, blog page and article
useQuery where necessary and pass data as props to concerned components
- index.html
- src/App.tsx
- src/components/Card.tsx
- src/components/Toaster.tsx
- src/routes/blogs/BlogT1.tsx
- src/routes/blogs/ListingBlogs.tsx
- src/routes/blogs/blogs.tsx
- src/routes/blogs/singleblog.tsx
- src/routes/createblog.tsx
- src/routes/home.tsx
- src/routes/singleArticle.tsx
- src/utils/interfaces/Interfaces.ts
- src/utils/ouputContentBlocks.tsx
- [e06-t11_connect_front_to_back](https://enchanting-triangle-00d.notion.site/e06-t11_connect_front_to_back-1e507c9000944a7081d293267d8688ef)

E06 t11 connect front to back

---

src/App.tsx
src/assets/EyeShow.svg
src/components/Navbar.tsx
src/components/buttons/DeleteUser.tsx
src/components/userSettings/EditUserForm.tsx
src/components/userSettings/UserInformations.tsx
src/contexts/UserContext.tsx
src/routes/login.tsx
src/routes/profile.tsx
src/routes/userSettings.tsx
src/utils/userInformationsValidation.ts

Display dynamic informations on the user profile page
Need to update user informations.
Disconnexion behaviour
UserContext missing infos
- Fetch user informations from database to display avatar, nickname and description on user profil page
- Create user form component to modify user informations and delete account whithout password modification. (react hook form + yup used)
- Redirect to homepage when the user logs out
- Add avatar url in userContext to display properly avatar in navbar
App.tsx
Navbar.tsx
src/components/buttons/DeleteUser.tsx
src/components/userSettings/EditUserForm.tsx
src/components/userSettings/UserInformations.tsx
src/contexts/UserContext.tsx
src/routes/login.tsx
src/routes/profile.tsx
src/routes/userSettings.tsx
src/utils/userInformationsValidation.ts
- [e03-t02]

E03 t02 profile page logged

---

src/components/Navbar.tsx
src/components/Toaster.tsx
src/components/buttons/DeleteUser.tsx
src/routes/profile.tsx
src/routes/register.tsx

feat(e03-t02): fix register, logout and account delete behaviour

---

src/components/Card.tsx
src/components/CardT2.tsx
src/components/createblog/StepThree.tsx
src/components/createblog/StepTwo.tsx
src/components/inputs/ProgressionBar.tsx
src/queries/blogs.ts
src/routes/blogs/BlogT1.tsx
src/routes/blogs/BlogT2.tsx
src/routes/blogs/EditDrag.tsx
src/routes/blogs/singleblog.tsx
src/routes/createblog.tsx
src/utils/blogValidation.ts
src/utils/interfaces/Interfaces.ts

:art:feat(epic0) rework of blog edition

---

package-lock.json
package.json
src/queries/blogs.ts
src/routes/blogs/BlogT1.tsx
src/routes/blogs/BlogT2.tsx
src/routes/blogs/EditDrag.tsx
src/routes/blogs/singleblog.tsx
src/utils/slug.ts

Please include a description of the changes and the related issue. Please also include relevant motivation and context.
Description of what I did/modified
package-lock.json
package.json
src/queries/blogs.ts
src/routes/blogs/BlogT1.tsx
src/routes/blogs/BlogT2.tsx
src/routes/blogs/EditDrag.tsx
src/routes/blogs/singleblog.tsx
- [e04-t05:](https://www.notion.so/e04-t05_blog-updating-6c950b090cca455090f5e847a8527400?pvs=4)

:lipstick:feat(e04_t05): maj edit blog

---

src/App.tsx
src/components/buttons/Pagination.tsx
src/components/buttons/StaticPagination.tsx
src/main.tsx
src/routes/articles.tsx
src/routes/blogs/BlogT1.tsx
src/routes/blogs/BlogT2.tsx
src/routes/blogs/ListingBlogs.tsx
src/routes/blogs/blogs.tsx
src/routes/discover.tsx
src/utils/ScrollToTop.tsx

I can explore blogs and articles 
- Update discovery page with limits on the getAllBlogsAndArticles query
- Update blogs and articles pages with limits and offsets on the queries
- Made the pagination component dynamic
- Add scroll to top functionnality
- App
- Pagination
- StaticPagination
- ListingBlogs
- Articles
- BlogT1 & BlogT2
- [e06-t01](link to issue)
Pour l'instant j'ai mis la limite d'articles et de blogs à afficher sur leurs pages respectives à 6 (plus facile pour vérifier que la pagination fonctionne si on n'a pas 10 000 blogs et articles en bdd), mais elle sera à modifier ultérieurement

E06 t01 exploration page

---

.github/workflows/front-test-epic-to-staging-pr.yml
.github/workflows/front-test-staging-to-main-pr.yml
package-lock.json
package.json
src/components/inputs/SearchBar.tsx
src/main.tsx
src/queries/articles.ts
src/queries/blogs.ts
src/queries/user.ts
src/routes/articles.tsx
src/routes/blogs/BlogT1.tsx
src/routes/blogs/BlogT2.tsx
src/routes/blogs/ListingBlogs.tsx
src/routes/discover.tsx
src/routes/home.tsx
src/routes/login.tsx
src/routes/profile.tsx
src/routes/register.tsx
src/utils/interfaces/Interfaces.ts
tests/WrappedContextProvider.tsx
tests/mocks.ts
tests/routesPages.test.tsx
tests/setup.js
tsconfig.json
vite.config.ts
vitest.config.ts

I want to search for blogs and articles by their names on their respective pages
I made the SearchBar component dynamic
Added input handling in the components that included SearchBar
Updated the testing mocks
- queries
- interfaces
- Search Bar
- BlogT1 & T2
- listing Blogs
- articles
- discover
- tests/ mocks
- [e00-t00:](link to issue)
---
Short description of the Epic and its purpose.
---
Description of all the modifications that will be added

E06 t02 search bar

---

.github/workflows/front-tests.yml

add docker file name

---

src/components/BlogCard.tsx
src/components/Card.tsx
src/components/CardT2.tsx
src/components/Logo.tsx
src/components/createblog/StepThree.tsx
src/routes/blogs/TemplateSelect.tsx
src/routes/home.tsx
vite.config.ts

Fix static assets for prod build

---

src/components/editor/EditorWrapper.tsx
vite.config.ts

Update vite config :
```js
build: {
commonjsOptions: {
transformMixedEsModules: true,
},
},
```

:ambulance: fix article editing page

---

docker-compose.yml

🚑 add volume directive to front compose service

---

src/components/editor/EditableArticle.tsx
src/components/editor/EditorTools.tsx
src/routes/blogs/articles/singleArticle.tsx

Review and fix article content versioning workflow

:bug: fix(epic05): fix versioning

---

docker-compose.dev.yml
package-lock.json
package.json
src/components/editor/EditableArticle.tsx
src/components/editor/EditorTools.tsx
src/components/editor/EditorWrapper.tsx
src/components/imagehandler/UpdateImage.tsx
src/queries/articles.ts
src/routes/blogs/articles/singleArticle.tsx
src/utils/interfaces/Interfaces.ts
src/utils/ouputContentBlocks.tsx

Retrieve latest features in article editing -> adding images to article content body
Améliorer la présentation des Editor Tools

:sparkles: add images to article content + improve editor tools ui

---

src/App.tsx
src/AppWrapper.tsx
src/components/Toaster.tsx
src/components/editor/EditableArticle.tsx
src/components/editor/EditorTools.tsx
src/components/editor/NewEditableArticle.tsx
src/queries/articles.ts
src/queries/comments.ts
src/routes/articles.tsx
src/routes/blogs/BlogT1.tsx
src/routes/blogs/BlogT2.tsx
src/routes/blogs/ListingBlogs.tsx
src/routes/blogs/articles/comments/Comments.tsx
src/routes/blogs/articles/newArticle.tsx
src/routes/blogs/articles/singleArticle.tsx
src/routes/blogs/singleblog.tsx
src/routes/discover.tsx
src/routes/profile.tsx
src/routes/publicProfile.tsx
src/routes/userSettings.tsx
src/utils/interfaces/Interfaces.ts

feat : Delete article from EditorTools
fix : getOneArticle comment cache collision & duplicate `<main>` html elements

:adhesive_bandage: fix getOneArticle comment & duplicate main elements

---

src/components/Card.tsx
src/components/editor/EditorTools.tsx
src/queries/articles.ts
src/queries/blogs.ts
src/routes/blogs/BlogT2.tsx
src/routes/blogs/singleblog.tsx

:sparkles: feat(stg): Save article cover url to db on update image

:sparkles: feat(stg): Save article cover url to db on update image
